name: Pixie Fabrics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9fa4b6'
    - '#f9ede0'
    - '#7dcbc2'
    - '#151a2d'
    - '#0b5783'
  brandStrength: 0.9189801779575646
  lightness: 0.6053387075662613
  saturation: 0.47728427639231086
  rhythmicContrast: 0.5000669835135341
purpose: []
