name: Pixie Fabrics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9fa4b6'
    - '#f9ede0'
    - '#7dcbc2'
    - '#151a2d'
    - '#0b5783'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
