name: Pixie Fabrics
favicon: null
layout_spectrum: 0.6827364014461637
typography_spectrum: 0.5738490079529583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9189801779575646
  lightness: 0.6053387075662613
  saturation: 0.47728427639231086
  rhythmicContrast: 0.5000669835135341
purpose: []
